version: 2.1

executors:
  bash:
    docker:
      - image: cimg/base:stable
  clojure:
    docker:
    - image: circleci/clojure:lein-2.8.1
  postgres:
    docker:
      - image: circleci/postgres:9.5.12-alpine # for integration test

commands:
  restore_and_save_cache:
    - restore_cache:
        key: << checksum "project.clj" >>
    - run: lein deps
    - save_cache:
        paths:
          - ~/.m2
        key: << checksum "project.clj" >>

jobs:
  test:
    working_directory: ~/data-spec
    executor:
      - name: clojure
      - name: postgres
    steps:
      - checkout
      - restore_and_save_cache
      - run: lein do test, cljfmt check

  deploy-dw:
    working_directory: ~/data-spec
    executor:
      - name: clojure
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    steps:
      - checkout
      - run: echo 'fill me out later'

  deploy-ddl:
    working_directory: ~/data-spec
    executor:
      - image: bash
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    steps:
      - checkout
      - run: sudo apt update; sudo apt install -qq bc jq python3-pip; pip3 install awscli --upgrade --user
      - run: deploy/bin/deploy-athena deploy-ddl

  repair-partitions:
    working_directory: ~/data-spec
    executor:
      - image: bash
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    steps:
      - checkout
      - run: sudo apt update; sudo apt install -qq bc jq python3-pip; pip3 install awscli --upgrade --user
      - run: deploy/bin/deploy-athena repair-partitions

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy-ddl:
          filters:
            branches:
              only:
                - master

      - repair-partitions:
          filters:
            branches:
              only:
                - master
          requires:
            - deploy-ddl
