version: 2.1

orbs:
  slack: circleci/slack@3.4.0

executors:
  bash:
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    working_directory: ~/data-spec
    docker:
      - image: cimg/base:stable
  clojure:
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    working_directory: ~/data-spec
    docker:
      - image: circleci/clojure:lein-2.8.1
  clojure_and_postgres:
    docker:
      - image: circleci/clojure:lein-2.8.1
      - image: circleci/postgres:9.5.12-alpine # integration test

commands:
  restore_and_save_cache:
    steps:
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: << checksum "project.clj" >>
  install_aws_cli:
    steps:
      - run: apt update; apt install -y -qq bc python3-pip; pip3 install awscli --upgrade --user

jobs:
  test:
    executor: clojure_and_postgres
    steps:
      - checkout
      - restore_and_save_cache
      - run: lein do test, cljfmt check

  deploy-dw:
    executor: clojure
    steps:
      - checkout
      - run: echo 'fill me out later'

  deploy-ddl:
    executor: bash
    steps:
      - checkout
      - install_aws_cli
      - run: deploy/bin/deploy-athena --task deploy-ddl

  repair-partitions:
    executor: bash
    steps:
      - checkout
      - install_aws_cli
      - run: deploy/bin/deploy-athena --task repair-partitions

  notify:
    executor: bash
    steps:
      - slack/notify:
          message: 'New version of datalake ddl deployed.'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy-ddl
      - repair-partitions:
          requires:
            - deploy-ddl
          filters:
            branches:
              only:
                - master
      - notify:
          requires:
            - repair-partitions
          filters:
            branches:
              only:
                - master
