version: 2
jobs:
  deploy-athena:
    working_directory: ~/datawarehouse-spec
    docker:
    - image: circleci/clojure:lein-2.8.1
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    steps:
      - checkout
      - run: sudo apt update; sudo apt install -qq jq; sudo apt install -qq python-pip; pip install awscli --upgrade --user
      - run: deploy/bin/deploy-athena

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy-athena:
          filters:
            branches:
              only:
                - master
